### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by nsde** [esteinmann/chatgpt-convdown#18]
You could use the `download` icon by Bootstrap-Icons.
I think it looks way better than the current one, and is licensed under MIT, which is pretty permissive:

https://icons.getbootstrap.com/icons/download/

<img height="100px" src="https://user-images.githubusercontent.com/67185896/218835039-1234940c-0d0e-4e0e-8169-f27c9cf34441.svg">

```svg


<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
  <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
  <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
</svg>
```

![image](https://user-images.githubusercontent.com/67185896/218834812-fa8db4a5-93af-4553-8702-ba5eff3e604a.png)

**Comment by esteinmann** [comment]
The bootstrap icon is now an option so closing this

**Comment by nsde** [comment]
nice!
