### ISSUE TITLE
File name end with ..md

### ISSUE THREAD

**Issue by mattjoyce** [esteinmann/chatgpt-convdown#24]
Not a huge issue, but I notice the file name ends with two period.
Here's an example, ChatGPT_20230219T120846605Z_TestSuccessful..md
Here's another, ChatGPT_20230219T120237907Z_Discordpluginsandbots..md

It might cause issues for some filesystems.
Maybe strip any trailing period.

**Comment by esteinmann** [comment]
Thanks, that shouldn't be too hard to fix.

> Maybe strip any trailing period.

That or just strip all periods from the conversation name when constructing the file name.
