### ISSUE TITLE
[Question] Why "Access browser activity during navigation" permission required?

### ISSUE THREAD

**Issue by SamuelMiller** [esteinmann/chatgpt-convdown#35]
Hello, Thanks for developing this extension. I am a little concerned about giving extension permission to "Access browser activity during navigation" permission in firefox safe?" Why does the extension require this permission and does the extension monitor other sites beside ChatGPT?

**Comment by mattjoyce** [comment]
I think the extension uses the webNavigation permission to inject a download button into the chat window's navigation bar. This button triggers the download of the conversation.

**Comment by esteinmann** [comment]
I consider this question as answered.
