### ISSUE TITLE
Would it be possible...

### ISSUE THREAD

**Issue by bonelifer** [esteinmann/chatgpt-convdown#44]
Would it be possible to download all chats?

**Comment by esteinmann** [comment]
Not with the current method of downloading the chat. The current method relies on the rendered elements on the page, so it only has access to the messages of the current visible conversation.

Another method would be by accessing the background API's response (a handy JSON representation of the conversation) that is used to render the chat by the web page. Then the extension would act like an adblocker (intercepting all HTTP requests on chat.openai.com) but without altering the content. This requires even more permissions. Using this method we could also get the bearer token en make our own calls to the backend API to download more chats.

But maybe the best solution for you would be the data export. IIRC you can download all your chats at once by exporting your data. I have not tried this but maybe this will give you the chats as JSON? If it's the same format as the background API uses then it's probably not hard to extract the chats as Markdown using a local script. The JSON that the API returns already contains the messages formatted in Markdown.

**Comment by esteinmann** [comment]
I consider this question as answered. It's unlikely this will be implemented any time soon.
