### ISSUE TITLE
Can you add shortcuts?

### ISSUE THREAD

**Issue by eiovrj** [esteinmann/chatgpt-convdown#45]
To the awesome developers, I really need the custom shortcut function, I really need it. Can you add this feature?"

**Comment by esteinmann** [comment]
Hello,

Which shortcuts do you mean? Or I should say which actions do you want a shortcut for? The extension has 2 actions currently. Downloading (by clicking on the button) or copy to clipboard (holding shift while clicking on download)

**Comment by eiovrj** [comment]
Sure, here's the translation:

"Thank you very much for the developer's response. I really need the shortcut to download, just like in Firefox settings where you can edit 'Manage Extension Shortcuts'."
![螢幕快照 2024-04-20 17-37-30](https://github.com/esteinmann/chatgpt-convdown/assets/130614414/0ebbdf32-12a0-4ccf-af8d-c49d55e10aac)

**Comment by esteinmann** [comment]
Ah thanks for the helpful screenshot, I didn't even know Firefox had this feature :) Do you have a suggestion for a default shortcut for downloading? I could add that to the manifest it seems: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

**Comment by eiovrj** [comment]
Dear developer, I suggest 'Ctrl + Alt + s' or 'Ctrl + Alt + x'. Both work perfectly fine for me under Ubuntu (Ctrl + Alt + D is a system shortcut: minimize all windows).

**Comment by esteinmann** [comment]
I will look into it. It's a little more complicated then I thought as I can only catch the command in the background script and then probably need to send a message to the download-button.js script to trigger the download action

**Comment by eiovrj** [comment]
No problem at all, we all appreciate your efforts. Thanks ,The output MD files can be directly imported into Obsidian without any modification.

**Comment by esteinmann** [comment]
For now I have the code for adding the shortcuts in this branch: https://github.com/esteinmann/chatgpt-convdown/tree/feature/commands 

You could try now if you like by checking out that branch and adding the extension in temporary mode by going to: about:debugging#/runtime/this-firefox and select the manifest.json file. When you still have the real extension installed things can look weird, you might see multiple download buttons or one version gives an error. With the new code Firefox should see the commands:

![image](https://github.com/esteinmann/chatgpt-convdown/assets/63729650/951c50a5-7ec6-476a-be85-99e179552f87)

I will probably make a new release tomorrow.

**Comment by eiovrj** [comment]
Thank you very much for the developer's response. This operation is far beyond my operational capabilities. I'll wait for the release of your new version. Haha, once again, thank you very much for being able to help everyone despite your busy schedule.
