### ISSUE TITLE
Thank u very much!!!!

### ISSUE THREAD

**Issue by eiovrj** [esteinmann/chatgpt-convdown#47]
Success, success, the function has come out, thank you very much for the developer for taking the time to modify this feature, I really appreciate it, this shortcut is super convenient for me.
![螢幕快照 2024-04-25 14-48-03](https://github.com/esteinmann/chatgpt-convdown/assets/130614414/2a17428b-79a0-4e41-b7a8-a40298ddb9a6)

**Comment by esteinmann** [comment]
You are welcome :)
