### ISSUE TITLE
Redirected to different site: really not supported?

### ISSUE THREAD

**Issue by gkfirst8** [esteinmann/chatgpt-convdown#48]
Hi,

https://chat.openai.com/chat gets auto redirected to https://chatgpt.com/c for me. Will it not work in that case at all? Or am I looking in the wrong place?

With kind regards,
Gerke

**Comment by winkywooster** [comment]
i have the same issue, and looking at the permissions for the extension, it's only requesting permissions for  `chat.openai.com` :
<img width="630" alt="Screenshot 2024-05-07 at 09 54 36" src="https://github.com/esteinmann/chatgpt-convdown/assets/1713616/f4ecf2a1-9c12-4517-9588-042313e763b7">

**Comment by esteinmann** [comment]
Hadn't noticed this myself but I see the same redirection behavior. Added the domain in the latest PR. Will publish a new version to the Mozilla hub

**Comment by winkywooster** [comment]
thanks @esteinmann
