### ISSUE TITLE
Download Individual Chats

### ISSUE THREAD

**Issue by camarajordan** [esteinmann/chatgpt-convdown#5]
Since the new feature of isolated chats came, The extension doesn't work since the URL has a code from a specific chat.

**Comment by esteinmann** [comment]
Thanks for reporting. Had not checked Chat GPT the last couple of days. That change is about to make this extension obsolete it seems as Chat GPT keeps the history itself now (to some extent). Will try a quick fix in the manifest.json file

**Comment by camarajordan** [comment]
For some reason, now I can see the Download button. Maybe just because the extension hasn't sync with Chat GPT.

**Comment by esteinmann** [comment]
I already pushed an update but it's not a great solution. Only seems to work on hard page reloads as that is the entry point for the content script to run. Need to re-add a background script and trigger adding download button from there.

**Comment by esteinmann** [comment]
I just updaten the main branch with the code for version 4.0. The download button should now re-appear when switching between individual chats. This required quite a few changes. Needed to use a background script again and sadly also require more permissions as before.

Will update the add-on on the Mozilla portal later today when I have more time.

**Comment by esteinmann** [comment]
@camarajordan  Can you try the latest version (4.0)? It should be available in Firefox now

**Comment by esteinmann** [comment]
I regard this as fixed in version 4.0 now
