### ISSUE TITLE
Various list do not format when downloaded

### ISSUE THREAD

**Issue by skippix** [esteinmann/chatgpt-convdown#51]
I am developing a local database application to catalog my conversations after I use chatgpt-convdown to download them. I'm simply parsing the text file and reformatting it into something useful. For the most part, it works, especially with plain vanilla responses. However, I haven't been able to develop any rules that consistently work for parsing list output.

For example, this prompt:  

I want you to help me design a container garden. What questions do you have of me to get this project started?

Produced this response:

![image](https://github.com/esteinmann/chatgpt-convdown/assets/4819748/2dab2b55-2b49-41d5-a62e-34b36cb07ba5)

However, when I downloaded it, I get this:

## ChatGPT
To get started on designing your container garden, I'll need some additional information to tailor the recommendations to your specific needs and preferences:Plant Preferences:Do you have any specific types of plants you want to include (e.g., flowers, herbs, vegetables, shrubs)?Are there any plants you definitely want to avoid?Container Details:What are the sizes and types of containers you plan to use?Do you have any preferences for the material of the containers (e.g., clay, plastic, wood)?Watering and Maintenance:How much time can you dedicate to watering and maintaining the garden?Do you have an irrigation system in place, or will you be watering by hand?Aesthetic Preferences:Do you have a particular color scheme or theme in mind for your garden?Are you aiming for a specific style (e.g., modern, rustic, cottage)?Planting Season:Are you planning to plant seasonally or looking for year-round interest?Budget:Do you have a budget for plants and materials?Other Considerations:Are there any local pests or wildlife that you need to account for?Do you have any soil preferences or requirements?Once I have this information, I can provide specific recommendations for plants that will thrive in your conditions and match your preferences.

----------------------------------------------------------------
I can provide other examples if you need them. I'm using the latest version of Firefox on a PC.

Thanks for anything you can do to address this.

**Comment by esteinmann** [comment]
Thank you for reporting the issue. Will look into this when I have the time. Can't promise anything though as I have little time to work on this extension. PRs are always welcome :)

**Comment by esteinmann** [comment]
It took waaay too long but finally had some time to work on this extension again. All special markdown formatting was broken due to changed DOM nodes for the conversation elements. Also there was no support yet for nested lists. Still need to upload a new version to Mozilla hub (7.2)
